# Shell tools
cask "iterm2"
brew "zsh"
brew "zsh-syntax-highlighting"
brew "tmux"
cask "1password-cli"
brew "kube-ps1"
cask "alacritty"

# ZSH
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
tap "romkatv/powerlevel10k"
brew "romkatv/powerlevel10k/powerlevel10k"

# Vim tools
brew "ripgrep"
brew "neovim"

# Source control tools
brew "hub"
brew "tig"
brew "lazygit"
brew "git-delta"

# Languages
brew "node@12"
brew "composer"

# PHP
brew "php-cs-fixer"

