# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="/Users/nickbabenko/.oh-my-zsh"

# Theme
ZSH_THEME="robbyrussell"

# Plugins
plugins=(
  git 
  kubectl 
  brew
  common-aliases 
  gitfast 
  zsh-syntax-highlighting
  docker
  docker-compose
  doctl
  zsh-autosuggestions
  helm
  vscode
  kubectl
)

export EDITOR='vim'

# Update path
export PATH=$HOME/bin:/usr/local/bin:$PATH
export PATH="$HOME/.composer/vendor/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"

[ -f ~/.kubectl_aliases ] && source ~/.kubectl_aliases

gitpush() {
  git add .
  git commit -am "$1"
  git push
}

# Aliases
alias k='kubectl'
alias gitpush="gitpush"

# Check for dotfile updates
source ~/dotfiles/bin/update.sh
